config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      get 'user/current'
    end
  end
  get 'likes/create'
  get 'likes/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # This defines a route rule that says when we receive
  # a GET request with the URL '/', handle it with the
  # WelcomeController with the index action inside that
  # controller.
  get('/', {to: 'welcome#index', as: 'root'})

  get '/contacts/new', {to: 'contacts#new' }
  post '/contacts', {to: 'contacts#create'}

  resources :users, only: [:new, :create, :show]

  # `resource` is singular instead of `resources`
  # Unlike `resources`, `resource` will create routes that
  # do CRUD operation on only one thing. There will be no
  # index routes, and no route will have an `:id`
  # wild card. When using a singular resource,
  # the controller must still be plural.
  resource :session, only: [:new, :create, :destroy]

  # # question new page
  # # when someone requests /questions/new it will be handled by the NEW method
  # # inside of questions controller
  # get '/questions/new', {to: 'questions#new', as: :new_question}
  # # get '/questions/:id', {to: 'questions#show', as: :question }
  #
  # # handles submission of new questions form
  # post 'questions', {to: 'questions#create', as: :questions}
  #
  # # question show page
  # # adding the alias `as: :question` will create the helper paths/url to question_path
  # # we can use these like so: question_path(<id>), question_url(<id>)
  # get '/questions/:id', {to: 'questions#show', as: :question}
  #
  # # question index page
  # get '/questions', {to: 'questions#index'}
  #
  # # question edit page
  # get '/questions/:id', {to: 'questions#edit', as: :edit_question}
  #
  # # handles submission of form on the question edit page
  # patch '/questions/:id', {to: 'questions#update'}
  #
  # delete '/questions/:id', {to: 'questions#destroy'}

  # this builds all of the above routes for us ;)
  # 'resources' method will generate all CRUD routes
  # following RESTful conventions for a resource
  # It will assume there is a controller named after the
  # first argument, pluralized and PascalCased
  resources :questions do
    # Routes written inside of a block passed to
    # a resources method will be pre-fixed by
    # a path corresponding to the passed in symbol.
    # In this case, all nested routes will be pre-fixed
    # with '/questions/:question_id'
    resources :answers, only: [:create, :destroy]
    # equivalent to:
    # resources :answers, except: [:show, :index, :new, :edit, :update]
    # question_answers_path(<question-id>),
    # question_answer_url(<question-id>)
    # question_answers_path(@question.id)
    resources :likes, only: [:create, :destroy]
    resources :publishings, only: :create
  end

  resources :job_posts, only: [:new, :create, :show, :destroy, :index]

  # The option `defaults: { format: :json }`
  # will set json as the default response for
  # all routes contained within the block
  # of the namespace.

  # The namespace method in Rails routes makes
  # it so it will automatically look in a
  # directory api, then in a sub directory v1
  # for QuestionsController.
  namespace :api, defaults: { format: :json } do
    # /api..
    namespace :v1 do
      # /api/v1...
      resources :questions
      # /api/v1/questions
      resource :session, only: [:create, :destroy]
      # /api/v1/user
      resources :users, only: [:create] do
        # api/v1/user/current
        get :current, on: :collection
        # default
        # api/v1/user/:id/current
      end
    end
  end

  get "/auth/github", as: :sign_in_with_github
  get "auth/:provider/callback", to: "callbacks#index"
  # get "auth/github/callback", to: "callbacks#index"
  # get "auth/twitter/callback", to: "callbacks#index"

  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post]
  )
end

app/models/question.rb
class Question < ApplicationRecord
  # This is the Question model. We generated this
  # file with the command:
  # rails g model question title:string body:text
  # This command also generates a migration file
  # in db/migrate

  # Rails will add attr_accessors for all columns
  # of the table (i.e. title, body, created_at, updated_at)

  # Adding 'dependent: :destroy' option tells Rails to
  # delete associated records before deleting the record
  # itself. In this case, when a question is deleted
  # its answers are deleted first to satisfy the foreign
  # key constraint.
  # You can also use 'dependent: :nullify' which will
  # cause all associated answers to have their question_id
  # column set to NULL before the question is destroyed.

  # If you don't use either dependent option, you can end
  # up with answers in your db referencing question_ids
  # that no longer exist, likely leading to errors.
  # Always set a dependent option to help maintain
  # referential integrity.
  belongs_to :user
  has_many(:answers, dependent: :destroy)
  # has_many(:answers, dependent: :destroy) adds
  # the following instance methods to the Question model:

  # .answers
  # .answers<<(object, ...)
  # .answers.delete(object, ...)
  # .answers.destroy(object, ...)
  # .answers=(objects)
  # .answers_singular_ids
  # .answers_singular_ids=(ids)
  # .answers.clear
  # .answers.empty?
  # .answers.size
  # .answers.find(...)
  # .answers.where(...)
  # .answers.exists?(...)
  # .answers.build(attributes = {}, ...)
  # .answers.create(attributes = {})
  # .answers.create!(attributes = {})
  # .answers.reload

  # Many to Many :likes
  # one way to define Many to Many
  # has_and_belongs_to_many :likes # but this way is discouraged because its too rigid

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user # this association is dependent on the has_many :likes association

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings#, source: :tag
  # If the name of the association (i.e. :tags)
  # is the same as the source singularized (i.e. :tag)
  # then the source argument can be omitted.
  has_one_attached :image


  # Create validations by using the 'validates' method
  # The arguments are (in order):
  # - A column name as a symbol
  # - Named arguments, corresponding to the validation
  # rules

  # To read more on validations, go to:
  # https://guides.rubyonrails.org/active_record_validations.html

  validates(:title, presence: true, uniqueness: true)

  validates(
    :body,
    presence: {message: "must exist"},
    length: { minimum: 10 }
  )

  validates(
    :view_count,
    numericality: {greater_than_or_equal_to: 0, allow_blank: true}
  )

  # Custom validation
  # The method for custom validations is singular
  # unlike the 'validates' method for regular validations
  validate :no_monkey

  # before_validation is a lifecycle callback
  # method that allows to respond to events during
  # the life of a model instance (i.e. being validated,
  # being created, being updated etc.)
  # All lifecycle callback methods take a symbol
  # named after a method and calls that method
  # at the appropriate time.
  before_validation(:set_default_view_count)

  include AASM

  aasm whiny_transitions: false do
    # Set the initial state for new instances
    # with 'initial: true'
    state :draft, initial: true
    state :published
    state :answered
    state :not_answered
    state :archived

    event :publish do
      transitions from: :draft, to: :published
    end

    event :answer do
      transitions from: [:not_answered, :published], to: :answered
    end

    event :no_answer do
      transitions from: :published, to: :not_answered
    end

    event :archive do
      transitions to: :archived
    end
  end



  #  For all available methods go to:
  # https://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks
  def cool_view_count
    view_count
  end

  # Create a scope with a class method
  # https://edgeguides.rubyonrails.org/active_record_querying.html#scopes

  # def self.recent
  #   order(created_at: :desc).limit(10)
  # end

  # Scopes are such a commonly used feature, that
  # there's another way to create them quicker. It
  # takes a name and a lambda as a callback
  scope(:recent, -> { order(created_at: :desc).limit(10) })

  scope(:viewable, -> {
      where(aasm_state: [:published, :answered, :not_answered])
    })

  # def self.search(query)
  #   where("title ILIKE ? OR body ILIKE ?", "%#{query}%", "%#{query}%")
  # end
  # Equivalent to:
  scope(:search, -> (query) { where("title ILIKE ? OR body ILIKE ?", "%#{query}%", "%#{query}%") })



  def tag_names
    self.tags.map{ |tag| tag.name }.join(", ")
  end

  # Appending = at the end of a method name, allows
  # us to implement a setter. A setter is a method that
  # is assignable

  # Example:
  # q.tag_names = "stuff, yo"

  # The code in the example above would call the method below, where the value on the right hand side of the = ("stuff, yo") would become the argument to the method (rhs)
  def tag_names=(rhs)
    self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
      # Finds the first record with the given
      # attributes, or initializes a record (Tag.new)
      # with the attributes if one is not found.
      Tag.find_or_initialize_by(name: tag_name)
    end
  end
  private

  def no_monkey
    # &. is the safe navigation operator. It's used
    # like the . operator to call methods on an object.
    # If the method doesn't exist for the object, 'nil'
    # will be returned instead of getting an error
    if body&.downcase&.include?("monkey")
      # To make a record invalid. You must add a
      # validation error using the 'errors' 'add' method
      # It's arguments (in order):
      # - A symbol for the invalid column
      # - A error message as a string
      self.errors.add(:body, "must not have monkeys")
    end
  end

  def set_default_view_count
    # If you are a writing to an attribute accessor, you
    # must prefix with 'self.' Which you don't need to do
    # if you are reading it instead.
    self.view_count ||= 0
  end

end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  rescue_from(ActiveRecord::RecordNotFound, with: :record_not_found)
  rescue_from(ActiveRecord::RecordInvalid, with: :record_invalid)

  def index
    questions = Question.order(created_at: :desc)
    render(json: questions, each_serializer: QuestionCollectionSerializer)
  end

  def show
    if @question
    render(
      json: @question,
      # We need to do this to make sure that Rails
      # includes the nested user association for answers
      # (which is renamed to author in the serializer).
      include: [ :author, {answers: [ :author ]} ]
    )
    else
      render(json: {error: 'Question Not found'})
    end
  end

  def create
    question = Question.new question_params
    question.user = current_user
    question.save!
    render json: { id: question.id }
  end

  def edit 
  end

  def update
    if @question.update question_params
      render json: { id: @question.id }
    else
      render :edit
    end

  end

  def destroy
    @question.destroy
    render(json: { status: 200 }, status: 200)
  end

  private

  def find_question
    @question ||= Question.find params[:id]
  end

  def question_params
    params.require(:question).permit(:title, :body, :tag_names)
  end

  def record_not_found
    render(
      json: { status:422, errors: {msg: 'Record Not Found'}},
      status: 422
    )
  end

  def record_invalid(error)
    invalid_record = error.record
    errors = invalid_record.errors.map do |field, message|
      {
        type: error.class.to_s,
        record_type: invalid_record.class.to_s,
        field: field,
        message: message,
      }
    end
    render(
      json: { status:422, errors: errors }
    )
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize!, only: [:edit, :update, :destroy]

  def new
    @question = Question.new
  end

  def create
    # # The 'params' object available in controllers
    # # is composed of the query string, url params,
    # # and the body of a form
    # # (e.g. req.query + req.params + req.body)
    #
    # # A good trick to see if your routes are working
    # # and you're getting the data that you want, is to
    # # render the params as JSON. This is like doing
    # # res.send(req.body) in Express

    # Use 'require' on the params object to retrieve
    # the nested hash of a key usually corresponding to
    # the name-value pairs of a form

    # Then use permit to specify all input names that
    # are allowable (as symbols).
    @question = Question.new question_params
    @question.user = current_user
    if @question.save
      flash[:notice] = "Question created successfully"
      # if question is saved successfully redirect to question show page
      redirect_to question_path(@question)
    else
      # render views/questions/new.html.erb
      render :new
    end
  end

  def show
    # For the 'form_with' helper
    @answer = Answer.new
    # For the list of answers
    @likes = @question.likes.count
    @answers = @question.answers.order(created_at: :desc)
  end

  def index
    if params[:tag]
      @tag = Tag.find_or_initialize_by(name: params[:tag])
      @questions = @tag.questions.viewable.order(created_at: :desc)
    else
      @questions = Question.viewable.order(created_at: :desc)
      respond_to do |format|
        format.html { render  }
        format.json { render json: @questions }
      end
    end
  end

  def edit
  end

  def update
    # attempt to edit the existing question with new values
    if @question.update question_params
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = "Question destoryed!"
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    # params.require(:question): We must have a question object on the params of this request
    # .permit(:title, :body): for security reasons we need to only permit the title and body keys/attributes of the question
    params.require(:question).permit(:title, :body, :tag_names, :image)
  end

  def find_question
    # get the current value inside of the db
    @question = Question.find params[:id]
  end

  def authorize!
    redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @question)
  end
end

app/views/questions/_form.html.erb
<%#
  To create a form for a resource (i.e. a model), use
  the form_wth helper instead of formm_tag. Its usual
  arguments are:
  - A named argument 'model' which is assigned an
  instance of a model (i.e. a new question)
  - A named argument 'local', which will prevent
  the form from submitting its data using AJAX.
  - A block that is passed the form object, where
   we build the HTML inside the form (i.e. labels,
   inputs, submission buttons, etc.)
    All data from the input fields a form built with this will have its name-value nested in a hash named
   after the class of the passed in model
   (e.g. <input type="text" name="question[title]" id="question_title"> => { "question": { "title": "What?"} })
%>

<% if @question.errors.any? %>
  <ul>
    <% @question.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%# https://guides.rubyonrails.org/form_helpers.html %>
<%= form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <div>
    <%= f.label :tag_names %>
    <%= f.text_field :tag_names %>
  </div>
  <div>
    <%= f.file_field :image %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<script>
  // Documentation for selectize.js:
  // https://selectize.github.io/selectize.js/

  // For a description of options that are useable
  // go to:
  // https://github.com/selectize/selectize.js/blob/master/docs/usage.md

  $("#question_tag_names").selectize({
    delimiter: ',',
    persist: false,
    labelField: "name",
    valueField: "name",
    searchField: "name",
    options: <%= Tag.select(:name).to_json(except: [:id]).html_safe %>,
    create (input) {
      return {
        name: input
      }
    }
  });
</script>

app/views/questions/edit.html.erb
<h1>Question Edit Page</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<% if @tag.present? %>
  <h6>
    Showing questions tagged by
    <span class="badge badge-pill badge-primary">
      <%= @tag.name %>
    </span>
  </h6>
<% end %>
<% @questions.each do |question| %>
  <div>
    <h2><%= link_to question.title, question_path(question) %></h2>
    <p><%= question.body %></p>
    <hr>
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>Question New Page</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<%= image_tag @question.image.variant(resize: '500X500') if @question.image.attached? %>

<p><%= @question.body %></p>
<p><%= @question.created_at %></p>
<p>
  Created by: <%= @question.user&.full_name || 'DELETED'  %>
</p>

<!-- <p>
  Tags:
  <%#= @question.tags.map{ |tag| tag.name }.join(", ") %>
  <%#= @question.tags.map(&:name).join(", ") %>
</p> -->
<div>
  <% @question.tags.each do |tag| %>
    <%= link_to(
      tag.name,
      questions_path(tag: tag.name),
      class: "badge badge-pill badge-primary"
    ) %>
  <% end %>
</div>

<% if @question.draft? && can?(:publish, @question)%>
  <%= link_to "Publish", question_publishings_path(@question), method: :post, class: "btn btn-primary btn-sm" %>
<% end %>

<div><%= @question.likes.count %></div>
<% like = @question.likes.find_by(user: current_user) %>
<% if like.present? %>
  <%= link_to "Un-like", question_like_path(@question, like), method: :delete%>
<% else %>
  <%= link_to "Like", question_likes_path(@question), method: :post%>
<% end %>

<% if can? :crud, @question %>
  <%= link_to "Edit", edit_question_path(@question)%>
  <%= link_to "Delete", question_path(@question), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>
<hr />
<%#
To create a form for a resource (i.e. a model), use the form_with
helper instead of the form_tag. Its usual arguments are:
- A named arg. model which is assigned an instance of a model
(e.g. a new question)
- A named arg. local which will prevent the form from submitting
its data using AJAX.
- A block that is passed the form object wherein we build
the HTML inside the form (e.g. labels, inputs, submission buttons, etc)
All data from the input fields a form built with this will have its
name-value nested in a hash named after the class of the passed in model.
(e.g. <input name="question[title]"> => { "question": { "title": "What?" } })
%>
<%= form_with(model: [@question, @answer], local: true) do |f| %>
<% if @answer.errors.any? %>
  <ul>
    <% @answer.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="form-group">
  <%= f.text_area(
  :body,
  cols: 50,
  rows: 5,
  placeholder: "What are your thoughts?",
  class: "form-control"
  ) %>
</div>
<%= f.submit "Answer" %>
<% end %>

<hr />

<ul class="answer-list">
  <% @answers.each do |answer| %>
    <li>
      <p>
        <%= answer.body %> <br />
        <% if can? :crud, answer %>
        <small>
          <%= link_to(
            "Delete",
            question_answer_path(@question, answer),
            method: :delete,
            data: {
              confirm: "Are you sure?"
            }
          ) %>
        </small>
        |
        <% end %>
        <small>
          Answered <%= time_ago_in_words(answer.created_at) %> ago
        </small>
      </p>
    </li>
  <% end %>
</ul>